PaddleClas:
  white: all
  black: none
PaddleGAN:
  white: all
  black: none
PaddleOCR:
  white: all
  black: none
PaddleVideo:
  white: all
  black: none
PaddleDetection:
  white: all
  black: none
PaddleSeg:
  white: all
  black: none
PaddleNLP:
  white: all
  black: none
PaddleRec:
  white: all
  black: none
PaddleSpeech:
  white: all
  black: none
PaddleSlim:
  white: all
  black: none
PARL:
  white: all
  black: none
