PaddleClas:
  white: all
  black: no
PaddleGAN:
  white: all
  black: no
PaddleOCR:
  white: all
  black: no
PaddleVideo:
  white: all
  black: no
PaddleDetection:
  white: all
  black: no
PaddleSeg:
  white: all
  black: no
PaddleNLP:
  white: all
  black: no
PaddleRec:
  white: all
  black: no
PaddleSpeech:
  white: all
  black: no
PaddleSlim:
  white: all
  black: no
PARL:
  white: all
  black: no
